# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import telegram_pb2 as telegram__pb2


class NewsTelegramStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNews = channel.unary_unary(
                '/NewsTelegram/GetNews',
                request_serializer=telegram__pb2.TranslatedNews.SerializeToString,
                response_deserializer=telegram__pb2.TranslatedNewsResponse.FromString,
                )


class NewsTelegramServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetNews(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NewsTelegramServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetNews': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNews,
                    request_deserializer=telegram__pb2.TranslatedNews.FromString,
                    response_serializer=telegram__pb2.TranslatedNewsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'NewsTelegram', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NewsTelegram(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetNews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/NewsTelegram/GetNews',
            telegram__pb2.TranslatedNews.SerializeToString,
            telegram__pb2.TranslatedNewsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
